---
- name: Memory and Swap usage monitoring
  hosts: all
  sources:
    - name: listen for alerts
      ansible.eda.alertmanager:
        host: 0.0.0.0
        port: 5000

  rules:
    - name: Host Memory or Swap High Action
      condition: >
        (event.payload.groupLabels.alertname == "hostMemUsageAlert" or 
         event.payload.groupLabels.alertname == "HostSwapIsFillingUp") and
        event.payload.status == "firing"
      
      throttle:
        once_within: 10 minutes
        group_by_attributes:
          - event.payload.commonLabels.instance

      action:
        run_job_template:
          name: EDA_demo_memory_usage_warning
          organization: Demo-1
          job_args:
            limit: "{{ event.payload.commonLabels.instance.split(':')[0] }}"
            extra_vars:
              alert_type: "{{ event.payload.groupLabels.alertname }}"